export const MEETING_ACTION_TYPE = "MEETING_ACTION_TYPE";
export const VIDEO_CAMERA_ON = "VIDEO_CAMERA_ON";
export const SCREEN_RECORD_ON = "SCREEN_RECORD_ON";
export const SHOW_SCREENSHAREPREVIEW_SCREEN = "SHOW_SCREENSHAREPREVIEW_SCREEN";
